platform :ios, '10.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/Dimi70/rigi-ios-sdk-Specs.git'

use_frameworks!

def install_pods
 pod 'Rigi', '1.3.0'
 pod 'GoogleSignIn', '5.0.1'
end

target 'Example2' do
  install_pods
end
